#!/bin/bash

# load aliases from bash profile
shopt -s expand_aliases
source ~/.bash_profile

# compile lexer file
antlr4 JavaLexer.g4 || exit 1

# compile parser file
antlr4 -no-listener -visitor JavaParser.g4 || exit 1

# compile java sources, including generated ones
/usr/bin/javac *.java || exit 1

echo "All done!"


