#!/bin/bash
gradle clean
mkdir -p src/generated/output
gradle run --args="src/tests/$*"
gradle copy
gradle delete
gradle compile

#mv *Out.java src/generated/output
#javac src/generated/output/Main.java

#java -cp src/generated/output Main


#if [[ "$*" == *"Main.java"* ]]
#then
#    java -cp src/generated/output Main
#else
#    thing="$*"
    #echo $thing
#    java -cp src/generated/output/ ${thing//".java"}
#fi
