#!/bin/bash
mkdir -p src/generated/output
gradle run --args="$*"
gradle copy
#mv *Out.java src/generated/output


javac src/generated/output/*.*
if [[ "$*" == *"Main.java"* ]]
then
    java src/generated/output/Main.java
else
    java src/generated/output/*Out.java
fi